"""Create user

Revision ID: 27f4cb1ac7b0
Revises: 002
Create Date: 2025-12-14 18:00:29.343146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27f4cb1ac7b0'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_accesses', 'view_access',
               existing_type=postgresql.ENUM('all_users', 'users_with_password', 'only_me', name='accesslevel'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('module_accesses', 'edit_access',
               existing_type=postgresql.ENUM('all_users', 'users_with_password', 'only_me', name='accesslevel'),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    op.drop_column('users', 'email')
    op.alter_column('module_accesses', 'edit_access',
               existing_type=sa.String(),
               type_=postgresql.ENUM('all_users', 'users_with_password', 'only_me', name='accesslevel'),
               existing_nullable=False)
    op.alter_column('module_accesses', 'view_access',
               existing_type=sa.String(),
               type_=postgresql.ENUM('all_users', 'users_with_password', 'only_me', name='accesslevel'),
               existing_nullable=False)
    # ### end Alembic commands ###
