"""Update int_rep 1

Revision ID: 0d23b0b7e239
Revises: 990fe2850855
Create Date: 2026-01-10 21:02:33.083643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d23b0b7e239'
down_revision = '990fe2850855'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval_repetitions', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_interval_repetitions_id'), 'interval_repetitions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interval_repetitions_id'), table_name='interval_repetitions')
    op.drop_column('interval_repetitions', 'id')
    # ### end Alembic commands ###
