"""Remove password hash

Revision ID: 7e80f1c7e2a7
Revises: bdebabf4a304
Create Date: 2026-01-16 11:36:34.559125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e80f1c7e2a7'
down_revision = 'bdebabf4a304'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_accesses', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_accesses', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
