"""Update int_rep

Revision ID: 990fe2850855
Revises: afa252cf3687
Create Date: 2026-01-10 20:53:25.885663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990fe2850855'
down_revision = 'afa252cf3687'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
