"""Create int_rep

Revision ID: afa252cf3687
Revises: 27f4cb1ac7b0
Create Date: 2026-01-10 20:41:03.807335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa252cf3687'
down_revision = '27f4cb1ac7b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval_repetitions', sa.Column('module_id', sa.Integer(), nullable=False))
    op.drop_index('ix_interval_repetitions_id', table_name='interval_repetitions')
    op.create_foreign_key(None, 'interval_repetitions', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_column('interval_repetitions', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval_repetitions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'interval_repetitions', type_='foreignkey')
    op.create_index('ix_interval_repetitions_id', 'interval_repetitions', ['id'], unique=False)
    op.drop_column('interval_repetitions', 'module_id')
    # ### end Alembic commands ###
