"""fix interval_repetitions id sequence

Revision ID: bdebabf4a304
Revises: 3390ea04f380
Create Date: 2026-01-16 10:09:37.881335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdebabf4a304'
down_revision = '3390ea04f380'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_interval_repetitions_id'), 'interval_repetitions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interval_repetitions_id'), table_name='interval_repetitions')
    # ### end Alembic commands ###
