"""Update int_rep 1

Revision ID: ccfb9aee0940
Revises: 0d23b0b7e239
Create Date: 2026-01-10 21:13:57.694844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfb9aee0940'
down_revision = '0d23b0b7e239'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
