"""Update int_rep 1

Revision ID: f0293ae565dc
Revises: ccfb9aee0940
Create Date: 2026-01-10 21:15:09.361740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0293ae565dc'
down_revision = 'ccfb9aee0940'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
